### ISSUE TITLE
Compiling error when building Client "runtime_error is not a member of std" - gcc 4.8.4

### ISSUE THREAD

**Issue by vincenzosantopietro** [votchallenge/trax#22]
Hi,
I'm building the client on Ubuntu 14.04 to test TraX integration by doing:
`cd path/to/TraX/support/client`
`cmake CMakeLists.txt`
`make`

I'm using gcc 4.8.4. 
When i type make i get the following errors: 

> /home/parallels/Downloads/trax-master/support/client/player.cpp: In function ‘trax::Image convert_image(cv::Mat&, int)’:
/home/parallels/Downloads/trax-master/support/client/player.cpp:69:15: error: ‘runtime_error’ is not a member of ‘std’
         throw std::runtime_error("No supported image format allowed");
               ^
/home/parallels/Downloads/trax-master/support/client/player.cpp: In function ‘int main(int, char**)’:
/home/parallels/Downloads/trax-master/support/client/player.cpp:278:23: error: ‘runtime_error’ is not a member of ‘std’
                 throw std::runtime_error(string("Unknown switch -") + string(1, (char) optopt));
                       ^
/home/parallels/Downloads/trax-master/support/client/player.cpp:323:23: error: ‘runtime_error’ is not a member of ‘std’
                 throw std::runtime_error("Tracker process not alive anymore.");
                       ^
/home/parallels/Downloads/trax-master/support/client/player.cpp:331:23: error: ‘runtime_error’ is not a member of ‘std’
                 throw std::runtime_error("Unable to initialize tracker.");
                       ^
/home/parallels/Downloads/trax-master/support/client/player.cpp:357:31: error: ‘runtime_error’ is not a member of ‘std’
                         throw std::runtime_error("Unable to contact tracker.");
                               ^
/home/parallels/Downloads/trax-master/support/client/player.cpp:376:27: error: ‘runtime_error’ is not a member of ‘std’
                     throw std::runtime_error("Unable to send new frame.");
                           ^
/home/parallels/Downloads/trax-master/support/client/player.cpp:384:14: error: expected type-specifier
     } catch (std::runtime_error e) {
              ^
/home/parallels/Downloads/trax-master/support/client/player.cpp:384:33: error: expected unqualified-id before ‘e’
     } catch (std::runtime_error e) {
                                 ^
/home/parallels/Downloads/trax-master/support/client/player.cpp:384:33: error: expected ‘)’ before ‘e’
/home/parallels/Downloads/trax-master/support/client/player.cpp:384:33: error: expected ‘{’ before ‘e’
/home/parallels/Downloads/trax-master/support/client/player.cpp:384:33: error: ‘e’ was not declared in this scope
/home/parallels/Downloads/trax-master/support/client/player.cpp:384:34: error: expected ‘;’ before ‘)’ token
     } catch (std::runtime_error e) {
                                  ^
make[2]: *** [support/client/CMakeFiles/traxplayer.dir/player.cpp.o] Error 1
make[1]: *** [support/client/CMakeFiles/traxplayer.dir/all] Error 2
make: *** [all] Error 2

I've edite the file player.cpp and added
`#include <stdexcept>`

Now it seems to work as expected.
Hope to have been helpful.

**Comment by lukacu** [comment]
Hi, thanks. I have noticed a similar issue somewhere in the past. Seems like it is not important anymore with newer GCC compilers but I will try the proposed fix for backwards compatibility.

**Comment by lukacu** [comment]
Hm, are you sure that you have checked the newest version? I have noticed that I have already added this include in the file.

**Comment by vincenzosantopietro** [comment]
Figured it out. 
I've downloaded TraX 4~5 days ago, and the include was added 3 days ago.
