### ISSUE TITLE
something wrong when running run_experiment.m with ncc example, using trax

### ISSUE THREAD

**Issue by he010103** [votchallenge/trax#23]
code:
function ncc
% ncc VOT integration example
% 
% This function is an example of tracker integration into the toolkit.
% The implemented tracker is a very simple NCC tracker that is also used as
% the baseline tracker for challenge entries.
%

% *************************************************************
% VOT: Always call exit command at the end to terminate Matlab!
% *************************************************************
cleanup = onCleanup(@() exit() );

% *************************************************************
% VOT: Set random seed to a different value every time.
% *************************************************************
RandStream.setGlobalStream(RandStream('mt19937ar', 'Seed', sum(clock)));

% **********************************
% VOT: Get initialization data
% **********************************
[handle, image, region] = vot('rectangle');

% Initialize the tracker
[state, ~] = ncc_initialize(imread(image), region);
try
    disp('1');
    gpuDevice(1);
catch err
    disp('wrong');
    warning(getReport(err));
end
disp('2');
while true

    % **********************************
    % VOT: Get next frame
    % **********************************
    [handle, image] = handle.frame(handle);

    if isempty(image)
        break;
    end;
    
	% Perform a tracking step, obtain new region
    [state, region] = ncc_update(state, imread(image));
    
    % **********************************
    % VOT: Report position for frame
    % **********************************
    handle = handle.report(handle, region);
    
end;

matlab log:
Error using traxclient
Did not receive response.

log:
@@TRAX:hello "trax.image=path;" "trax.region=rectangle;" "trax.version=1"
@@TRAX:initialize "file:///local/home/share/hezhiqun/model_zoo/vot-toolkit-fan/sequences/bag/00000001.jpg" "292.2300,128.3600,145.9600,132.4700"
@@TRAX:state "292.2300,128.3600,145.9600,132.4700"
@@TRAX:frame "file:///local/home/share/hezhiqun/model_zoo/vot-toolkit-fan/sequences/bag/00000002.jpg"
1

question: The program terminates in the 'gpuDevice(1)'. However, the ncc example can running successfully when setting 'tracker_trax = false'. So is there any bug when using gpuDevice in the trax?

**Comment by lukacu** [comment]
What about if you comment out the gpuDevice function? I guess it is not needed for NCC example, so at least it will be clear if this is the problem.
The protocol itself does not limit any functionality on its own, the only option is that there is a linking problem or some other error in gpuDevice.

**Comment by he010103** [comment]
The ncc program run successfully when commenting out the gpuDevice function. I need to use this function to select the gpu when running the DCFNet. I found this bug when running the DCFNet with trax. So I move the gpuDevice function to ncc example, the ncc example terminated in the code 'gpuDevice(1)'. But if I don't use trax, the code 'gpuDevice(1)' run without error.

**Comment by lukacu** [comment]
Can you try enabling TraX debug in the toolkit (set_global_variable('trax_debug', true))? There is a possibility that the gpuDevice function takes really long time to finish (at least this is what we have noticed). TraX client has a timeout of 30 seconds so if no response is received in that time it will kill the tracker.

**Comment by he010103** [comment]
Thanks！It works when setting the timeout larger.

**Comment by lukacu** [comment]
Great, in the future I recommend debugging these kind of issues using run_test as it turns on debug to terminal so that you can see all debug messages if there is anything meaningful written there.

**Comment by xiaoxiaohahahaha** [comment]
Can you tell me where exchange the value of timeout? I have changed the value of timeout  to 100000 in traxclient.m mexFunction, but there still have mistake that Error using traxclient: Did not receive response.
