### ISSUE TITLE
trax server failed to restart?

### ISSUE THREAD

**Issue by addvaluejack** [votchallenge/trax#25]
Hi,

I tried "run_experiments.m" several times, but it always stopped at the same location. Here is the log files.
[20170626T144410.log.txt](https://github.com/votchallenge/trax/files/1103254/20170626T144410.log.txt)
[20170626T145820.log.txt](https://github.com/votchallenge/trax/files/1103238/20170626T145820.log.txt)

It looks like the server failed to restart when last session is over. Is there any way I can fix it? Thank you very much.

P.S. I am using Windows 10 + VS 2015 + trax-1.2.0-windows64_vs14.zip

**Comment by lukacu** [comment]
Hm, there is nothing in the logs that would help me debug this, can you try enabling trax debug? You can do this by setting global variable trax_debug to true in the configuration file.

**Comment by addvaluejack** [comment]
Hi lukacu,

Thank you very much for your time. Here are the logs with trax_debug on.
[20170705T145633.log.txt](https://github.com/votchallenge/trax/files/1125751/20170705T145633.log.txt)
[20170705T145936.log.txt](https://github.com/votchallenge/trax/files/1125750/20170705T145936.log.txt)

**Comment by lukacu** [comment]
Hm, we have experienced similar problems before. The problem appears only on Windows in case the tracker misbehaves somehow because certain IO operations are implemented differently on Windows than on Posix systems. At the moment this is all I can say, we are trying to find a cause.

**Comment by addvaluejack** [comment]
Thank you for your reply. I think I will try to run my program on Linux system then.

Hoping you find the cause and solve it soon.

**Comment by lukacu** [comment]
I will close this issue since the mechanism for running trackers has changed a lot since it was opened.
