### ISSUE TITLE
Using Trax on Linux tutorial - problem

### ISSUE THREAD

**Issue by wvmcastro** [votchallenge/trax#26]
Hi, I am trying to do the Trax tutorial from the site, but I always get that is "Unable to start process". Below follows the full log. I really hope to use Trax on a university thing, please help as soon as possible, thanks !

Full log:
CLIENT: Creating process  "ncc_tracker" 
CLIENT: Starting process
CLIENT: Unable to start process
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Stopping watchdog thread
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 1)
Error: Unable to start the tracker process

**Comment by lukacu** [comment]
This is probably more suitable for the VOT support forum. It looks like the process cannot be executed, the typical reason for that is that the system cannot find the executable (e.g. not in the working right directory). If you still have issue with it I suggest that you look at the support forum.
