### ISSUE TITLE
TraX Image Formats: memory and data are inefficiency

### ISSUE THREAD

**Issue by cybertk** [votchallenge/trax#29]
In the current version(v1.2) of TraX protocol, both **memory** and **data** image format are base64 encoded, it's not very efficiency as

1. Size of encoded text increased 1/3
1. Require extra encoding/decoding cost

Considering the purpose of TraX is not only serving tracker evaluations, it's necessary to improve the protocol performance. Even for tracker evaluations, interference of image I/O can be removed by using memory/data image format.

Draft proposals, 
1. Convert from current text based protocol to binary protocol, like [Protocol Buffers](https://github.com/google/protobuf)
1. Adapting a  HTTP Multipart(defined in [RFC 1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html)) like solution, key is involving a **boundary** to protect the raw binary data between texts.

**Comment by lukacu** [comment]
Interesting ideas, discussion is indeed valuable as I have also noticed that the current approach is not fast, but I would really prefer to have a simple solution without any dependencies. Theoretically we could have more options, but there is also a lot of opportunities for improvement in the code itself (reading and writing messages are not implemented that efficiently with a lot of passes over memory).

**Comment by lukacu** [comment]
The most fruitful part of the discussion is now in #31, I will close this issue since it will not be fixed in the TraX protocol. One can perhaps start a new protocol if speed is really an issue.
