### ISSUE TITLE
Does it support for mac os x?

### ISSUE THREAD

**Issue by minglinlu** [votchallenge/trax#35]
I'm coding on mac, but I need to use this lib, and I don't see a mac os installation.

**Comment by lukacu** [comment]
Mac OSX is supported, you need CMake and XCode, then you can easily compile the library.

**Comment by minglinlu** [comment]
Emmm... Hope a tutorial_mac.rst is available under the folder `docs` ~ I'm trying now.><

**Comment by lukacu** [comment]
There is no tutorial, it is just basic CMake stuff, but you have to know a few things about using CMake and general software development for Unix. I do not have a Mac so I cannot modify the Linux tutorial reliably, but if you find where the differences are I will be more than happy to integrate them into a separate tutorial.

**Comment by minglinlu** [comment]
Mac is fine with `tutorial_compiling.rst`, and everything goes well according to the simple steps `cmake -DBUILD_OPENCV=ON -DBUILD_CLIENT=ON ..` .
However, I think you notice that another project might be something wrong. 
https://github.com/lukacu/mil/issues/2

**Comment by lukacu** [comment]
Closing outdated issue, seems resolved.
