### ISSUE TITLE
I use the new vot-toolkir-master ,i want test the sample 'ncc'; 1 toolkit_path;2 workspace_create;3 I select '1-test',NCC,'1-Matlab';and i have edit the tracker_NCC.m: tracker_label = ['NCC'],tracker_command = generate_matlab_command('ncc', {'F:\vot-toolkit-master\vot-toolkit-master\tracker\examples\matlab'}); But when I run_test ,it meet a error:Tracker has not passed the TraX support test;

### ISSUE THREAD

**Issue by xiaotian3** [votchallenge/trax#38]

**Comment by lukacu** [comment]
Please do not paste entire message in issue title, also this is not a TraX issue as such, but a VOT question that belongs to the VOT support forum.

**Comment by xiaotian3** [comment]
I am so sorry to bring some problem to you. I try to no use the ncc ,and use the vot 2017 trackers for example mosse_ca ,that is sucessful ! But ncc is not successful!

**Comment by lukacu** [comment]
Yes, but you cannot just post this all in a title, you can see that it is not even formatted. Please start a topic on the VOT support forum, but first check other topics, because we had similar issues a couple of times already.
