### ISSUE TITLE
When using CMAKE, there is a problem with trax-config.cmake

### ISSUE THREAD

**Issue by TwordPPK** [votchallenge/trax#43]
When using CMAKE, there is a problem with trax-config.cmake at 
https://github.com/vojirt/kcf,
CMake Error at E:/ELECTRIC/C++/github/KCF&SAMF/traxsourcebuild/trax-config.cmake:46 (MESSAGE):
   TraX component core not available.
Call Stack (most recent call first):
   CMakeLists.txt: 27 (FIND_PACKAGE)

**Comment by lukacu** [comment]
Probably a version issue. The KCF version that you are referring to may not be updated for newer libtrax. In any case, I am closing the issue, please check if you can submit a fix to the tracker repository.
