### ISSUE TITLE
Passed in MATLAB tracker but failed in PYTHON tracker

### ISSUE THREAD

**Issue by AstoncPou** [votchallenge/trax#44]
Hello, I test this toolkit with tutorial in http://www.votchallenge.net/howto/workspace.html

I successfully integrated tracker written in MATLAB,
tracker_label = [];
tracker_command = generate_matlab_command('ncc', {'/home/astonc/vot-toolkit-master/tracker/examples/matlab'});

tracker_interpreter = 'matlab';

after that, I tested integrating tracker written in python and failed.

tracker_label = [];
tracker_command = generate_python_command('python_ncc', {'/home/astonc/vot-toolkit-master/tracker/examples/python'});
tracker_interpreter = 'python';

Error log :

 run_experiments
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker ncc.
Tracker execution interrupted: Unable to start the tracker process
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.
Error in run_experiments (line 8)
tracker = tracker_load('ncc');

@lukacu,Could you help? Thank you so much!

**Comment by xi-mao** [comment]
I also meet the problem. someone can explain to me?

**Comment by AstoncPou** [comment]
i guest you os is windows, run it in ubuntu ,you will find it work right

**Comment by lukacu** [comment]
I think this has been resolved already in the toolkit issue tracker, closing.
