### ISSUE TITLE
MEX cannot find library 'ut'

### ISSUE THREAD

**Issue by YouaremyApple** [votchallenge/trax#45]
The error comes from these sentence :
arguments{end+1} = '-lut';  ( compile_trax>build_mex (line 51))
I can not figure out  where is the 'ut.lib', please help!

**Comment by lukacu** [comment]
Please provide more information, this problem can occur on Windows if your Matlab does not provide libut.lib I guess. But you can generate this file.

**Comment by huangbiubiu** [comment]
@lukacu I meet the same problem. How to generate this file?

**Comment by lukacu** [comment]
https://stackoverflow.com/questions/9360280/how-to-make-a-lib-file-when-have-a-dll-file-and-a-header-file
