### ISSUE TITLE
installing trax in ubuntu 18.04

### ISSUE THREAD

**Issue by youssefoumate** [votchallenge/trax#46]
Hello,
I'm trying to install trax in ubuntu 18.04 using this command:
sudo add-apt-repository ppa:lukacu/trax
However, I get this error message:
http://ppa.launchpad.net/lukacu/trax/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Can you please help me to fix this?

**Comment by lukacu** [comment]
Not really a problem for issue tracker, also the PPA is a bit outdated, there are no packages for Bionic there.
