### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by lukacu** [votchallenge/trax#5]
Python support can be implemented using native Python code or by wrapping the  the C library.

**Comment by alessiodore** [comment]
I have implemented a basic native Python socket server to handle the communication with the TraX client. I forked the TraX repository and added the python folder with the server a simple test. The forked repository is here [https://github.com/alessiodore/trax].

**Comment by alessiodore** [comment]
@lukacu I have forked the vot-toolkit repo [here](https://github.com/alessiodore/vot-toolkit) and added a simple test to run the evaluation (in tracker/examples/python). I can run the test with the C++ static_cpp "tracker". When I try to run the Python test I get a connection error from the Python TraX server. This is the error:

> octave:2> run_test
> Initializing VOT environment ...
> tracker_command = python /home/alessio/ext_lib/vot-toolkit/tracker/examples/python/static.py
> warning: implicit conversion from matrix to sq_string
> warning: implicit conversion from matrix to sq_string
> Testing TraX protocol support for tracker static.
> Error: Unable to establish connection.
> TraX support is not present.
> 
> ***************************************************************************
> 
> Welcome to the VOT workspace testing utility!
> This process will help you prepare your tracker for the evaluation.
> When beginning with the integration it is recommended to follow the steps 
> a, b, c to verify the execution and the output data.
> 
> ***************************************************************************
> 
> Choose action:
>   a - Generate a directory with input data for manual test
>   b - Run tracker once within the evaluation
>   d - Enable debug output
>   e - Exit
> Choose action: b
> Choose a sequence:
>   1 - "motocross"
>   2 - "sunshade"
>   3 - "surfing"
> Selected sequence: 1
> Sequence "motocross"
> INFO: Socket created
> ERROR: Connection failed. Error Code : 111
> Message: Connection refused
> error: No result produced by tracker. Stopping.
> error: called from:
> error:   /home/alessio/ext_lib/vot-toolkit/tracker/system_wrapper.m at line 220, column 9
> error:   /home/alessio/ext_lib/vot-toolkit/tracker/system_wrapper.m at line 31, column 12
> error:   /home/alessio/ext_lib/vot-toolkit/workspace/workspace_test.m at line 75, column 30
> error:   /home/alessio/wirewax_git/vot-workspace/run_test.m at line 10, column 1

The server error log  is not very helpful(ERROR: Connection failed. Error Code : 111 Message: Connection refused) . I am not sure if I am setting the correct port and ip. I am using the ones I found in the C code as default (127.0.0.1 port 9090). In the test I added in trax I launch the C client and then start the python server and they can communicate. 

When the run_test script starts does it create the client? I cannot figure out why the connection is refused when I use the Python server. Thank you!

**Comment by lukacu** [comment]
Yes, the problem is in the TraX support detection, if the support is not detected then the toolkit switches to the legacy mode which is not supported by your tracker. Is all the code submitted in your repository? I will check it out, but I will probably not do it right away because I am attending a conference. I agree that the current messages are not very helpful, we are working on that.

**Comment by alessiodore** [comment]
Thank you, Luka. Yes the code in the two forks I made from the [trax](https://github.com/alessiodore/trax) and [vot-toolkit](https://github.com/alessiodore/vot-toolkit) repositories. I haven't added the installer for the Python TraX server so when you use it in the "static tracker" test you need to add the TraX server path to the Python path (line 11 in vot-toolkit/examples/python/vot.py). 

I have seen that the detection happens in vot-toolkit/tracker/trax_test.m but I am not quite sure what the reason is. If I have time I will try to understand what is going wrong. If I can fix it before you can look at it I will report it here. Thank you.

**Comment by lukacu** [comment]
Just another comment, you do not have to fork the toolkit, it is better to test the tracker just using traxclient and keep everything in the trax repository for now. It is also more easy to turn on debug and get some additional information.

**Comment by alessiodore** [comment]
I fixed the problem with the TraX support not present. I had to add the "-X" option when trax_test.m runs with a Python tracker (I added a check for the tracker interpreter in trax_test.m). I have tested already the server with the trax client outside the toolkit and it works. Now the problem is that when I try to run the evaluation with the Python test static tracker I get the following error:

> octave:10> run_test
> Initializing VOT environment ...
> tracker_command = python .../vot-toolkit/tracker/examples/python/static.py
> warning: implicit conversion from matrix to sq_string
> Testing TraX protocol support for tracker static.
> TraX support is present.
> 
> ***************************************************************************
> 
> Welcome to the VOT workspace testing utility!
> This process will help you prepare your tracker for the evaluation.
> When beginning with the integration it is recommended to follow the steps 
> a, b, c to verify the execution and the output data.
> 
> ***************************************************************************
> 
> Choose action:
>   a - Generate a directory with input data for manual test
>   b - Run tracker once within the evaluation
>   d - Enable debug output
>   e - Exit
> Choose action: b
> Choose a sequence:
>   1 - "motocross"
>   2 - "sunshade"
>   3 - "surfing"
> Selected sequence: 1
> Sequence "motocross"
> Error: Unable to establish connection.
> Printing command line output:
> -------------------- Begin raw output ------------------------
> INFO: Socket created
> ERROR: Connection failed. Error Code : 111
> Message: Connection refused
> 
> --------------------- End raw output -------------------------
> error: Error during tracker execution.
> error: called from:
> error:   .../vot-toolkit/tracker/trax_wrapper.m at line 211, column 2
> error:   .../vot-toolkit/workspace/workspace_test.m at line 75, column 30
> error:   .../vot-workspace/run_test.m at line 10, column 1

What happen is that the TraX support detection runs the client with -Q option (query mode) which just try to connect with the server and then sends a quit message (which the server receives and handles) and exits. When I select the option 'b' (Run tracker once within the evaluation) the server starts again but it looks like the client doesn't. So this causes the "connection failed error". I tried to look at the C++ test but it looks like it uses the old file based method (correct me if I am wrong). I tried to run the Matlab test which should use the socket method but it doesn't work for me. I print the command passed to trax_test and it seems it is trying to use matlab even thought I only have octave installed:

> Testing TraX protocol support for tracker static.
> INFO: Executing ".....ext_lib/vot-toolkit/native/traxclient -Q -t 30 -e "TRAX=1" --** /usr/bin/matlab **-nodesktop -nosplash -r "try; addpath('..../vot-toolkit/tracker/examples/matlab');addpath('.../vot-toolkit/native/mex');ncc; catch; quit; end;"".
> Error: Unable to establish connection.
> TraX support is not present.

Can you explain to me what happen when the evaluation tool runs with the socket client? I think I am missing something. Why isn't the client started again when I try to evaluate the tracker?

**Comment by alessiodore** [comment]
I think I got it working now. It is a bit of a hack but I added a sleep in my static tracker loop. I didn't really fix the problem but I think at the moment it is a reasonable compromise. To try it out please clone my [fork](https://github.com/alessiodore/vot-toolkit) of the vot toolkit. I have added the trax.py server to the folder to avoid having to add the location to the Python path. My tracker configuration file looks like this:

tracker_label = ["static"];
% Now you have to set up the system command to be run.
% For classical executables this is usually just a full path to the executable plus
% optional arguments:
tracker_command = "python <path>/vot-toolkit/tracker/examples/python/static.py"

tracker_interpreter = ["python"]; % Set the interpreter used here as a lower case string. E.g. if you are using Matlab, write 'matlab'. (optional)

% tracker_linkpath = {}; % A cell array of custom library directories used by the tracker executable (optional)

**Comment by alessiodore** [comment]
I've tested the Python server in the toolkit and everything seems to work okay. I had some problem generating the report but that is not related to the Python socket server (I had error even trying to compare trackers benchmarked trackers). 

I had another weird bug that I fixed. When I was running the toolkit I was getting an error after ~100 frames regardless the sequence I was trying. The tracker run correctly on the sequences outside the toolkit (initializing it using the gt). The error was just:

> --------------------- End raw output -------------------------
> error: Error during tracker execution.
> error: called from:
> error:   .../vot-toolkit/tracker/trax_wrapper.m at line 211, column 2
> error:   .../vot-toolkit/workspace/workspace_test.m at line 75, column 30
> error:  .../vot15-workspace/run_test.m at line 10, column 1

I had some print to stdout in my tracker for debugging purposes. I didn't get any of my print on the printed raw output in the toolkit. But I got the log from the server. For them I used the logging module in Python. Replacing the normal print function with the logging module function fixed the problem. I am not sure why this happened but it looks like it has something to do with how print and logging write to stdout and how Matlab (in my case Octave) buffers them. I could recreate the problem just by adding a print with a long string in the static.py test in vot-toolkit/tracker/examples/python . @lukacu let me know if you know what the problem could be and if you want me to send the script to recreate the problem.

**Comment by lukacu** [comment]
Hey, thank you for the great work. I have checked at the code and it looks ok, we can probably make it official soon. There is just one thing that bothers me: why you are only supporting socket communication? By default the protocol works over stdin and stdout, which makes it easier to debug, are there any practical reasons why this would not work in Python?

**Comment by lukacu** [comment]
Ok, so I took some time to look at the implementation and I have noticed that there are a lot of functionalities that are missing. I am beginning to wonder if implementing everything in pure Python is actually a good idea since we do not have enough man-power to support it. There is a lot of region parsing already done in C, I have also implemented additional file formats there now. Perhaps using ctypes may not be such a bad idea, I will think about it and do some tests.

**Comment by alessiodore** [comment]
I think I can implement the communication over stdin and stdout. I can use sys.stdout.write and sys.stdin.read . But why is it useful if the socket solution works? How does it make it easier to debug?

I appreciate that supporting a separate implementation might not be efficient. This was my thought when I wrote on the forum. Anyway, which functionalities are missing? When I started implementing in you told me to look at the  white paper. I had to look at the C implementation and I replicated the functions used by the tracker examples. I am running the evaluation and it works for me.

**Comment by lukacu** [comment]
Like I have said, there is region parsing and all that. Perhaps it is not a lot since we do not need overlap calculation routines, I am just a bit worried about maintaining two implementations. I have only recently done some work with ctypes and found the approach very interesting this is why I am considering it as an alternative. But on the other hand it is true that all the long and boring conversions in C can be done much easier in Python. 

The standard input and output are traditionally used as the default mode of operation since they have wide applicability and do not rely on any networking libraries. I have only added network sockets recently as a hack to support Matlab on Windows here it is impossible to communicate using streams. In Python the simplicity is perhaps not the case, but it would be nice to have enough abstraction to support both approaches, especially so that new clients can be written that support all trackers.

As for the ease of debugging it is perhaps a matter of individual preference, but the protocol was designed so that it is embedded in the debug output of the trackers. This way the client has access to the debug outputs and the messages and can display both. For me this is quite nice. Mind though that VOT toolkit is not the place where you should debug your integration, this is why it supports generation of a testing script so that you can test your tracker outside of the environment.

**Comment by alessiodore** [comment]
Have you look at my implementation of vot.py in my fork of the [vot-toolkit](https://github.com/alessiodore/vot-toolkit). I have implemented the parser for the rectangular region. I haven't implemented the one for the polygon as I couldn't find the groundtruth and my tracker returns rectangles. It will be straightforward to implement the parsing of polygon regions. Is there more than that missing?

Considering the fact that it is now a working implementation and that at the moment there isn't an alternative implementation, I am not sure I understand the reason behind dismissing it without making it available to the community. I spent time on it because I found it useful for testing my tracker but I was also hoping it could have been helpful to other people using Python.  Also, the socket module in Python is available the default distribution so there is no need to install it. It is also very easy to use it to test a tracker. You can just copy two files, trax.py and vot.py in the folder where the tracker script is. I can add a setup.py to add it as a module but I am not sure it is a good idea for something so specific. As I said I run the evaluation for my tracker on the VOT15 dataset without any issue. When I have a bit of time I can try to use stdin and stdout. It should be easy and I can add it as an alternative class to use. 

What are you referring to with this:
> As for the ease of debugging it is perhaps a matter of individual preference, but the protocol was designed so that it is embedded in the debug output of the trackers. This way the client has access to the debug outputs and the messages and can display both. For me this is quite nice. Mind though that VOT toolkit is not the place where you should debug your integration, this is why it supports generation of a testing script so that you can test your tracker outside of the environment. 

If you are talking about the issue I reported when having print in my tracker that was to highlight a possible bug in the client not a problem I had in using the tool to debug my tracker. It looks like the output of the print function is read somewhere by the toolkit or by the client even when using the socket. It is not a problem for me as I fixed by using the logging library to output the tracker logs (not sure why the logging module is not causing issues) but it might be a problem if someone else is using it and they have print in their code.

**Comment by lukacu** [comment]
Well this is an open discussion, I am simply thinking about all possible alternatives. I agree that I was perhaps a bit to quick to jump on the ctypes alternative, but what I would like to stress that trax protocol goes a bit beyond VOT toolkit, there are other ways to use it too. If there are some additional representations in your toolkit fork I have not considered them at the moment since I have only checked the trax fork. The fact is that region parsing should be a part of the trax repository otherwise there will be a lot of confusion.

I understand that you are mostly keen on have your experiments performed, I am just commenting on the greater picture here. You have done a lot already and we at the votchallenge team appreciate it, but we will have to consolidate the code a bit more before it can be merged to the master branch.

**Comment by alessiodore** [comment]
I am keen to make my implementation of the server compliant with the requirements of the TraX protocol if this solution will be accepted as part of the TraX repository. If you think that this solution is difficult to maintain and you prefer to investigate other options it is fine to me but I am not going to spend time on my implementation as it works for my purpose as it is now. Just to make you understand my situation, I don't work in academia and, most likely, I am not going to publish my results but I am using them within my company as a baseline. The work I am doing on this is in my spare time and I will do it only if useful to the community. I think the work you and the votchallenge team has done is extremely valuable and I would be happy to give my contribution.

If you think that a native Python server is an acceptable option, I would appreciate if you could spend a bit of time to give me the spec of what are the missing functionalities and possibly how to test it. From our previous messages I understand that you would like to include:
- stdin and stdout implementation of the server - this should be easy enough. 
- region parsing in the trax repositiory. - again this should be straightforward as I have it already for the rectangular region in vot-toolkit. I would need an example of the polygon format that the protocol accept/expect. In Section 5.1 of the white paper it is not too clear how it should be formatted. Is it just a string: "x1,y1,x2,y2,...,xn,yn"? Do they need to be ordered or this is left to the tracker implementation?

Is there anything else? Thanks!

**Comment by lukacu** [comment]
Great to hear that the toolkit is also useful in the industry. I think that standard streams and region parsing are the two most required parts that have to be integrated in this repository to make the implementation complete. Well, actually it will not be complete, I have added preliminary support for other image types so this will have to be added as well and for that the message parsing code will have to be changed to be more efficient. But if you finish with these two parts it will be enough for now, I will then look at the code and perhaps make some changes (since I have some idea where the protocol will be extended). Thanks.

**Comment by alessiodore** [comment]
I have implemented the files stream implementation of the server. I have reorganized the code a bit to handle the two types of servers with inheritance. I could probably improve the structure a bit but I think as it is now should be modular enough and easy to understand. The default server is now the standard stream server. You can use the socket one by using the option attribute comm_type. I have moved the region parsing to trax.py. Everything is in my [trax fork](https://github.com/alessiodore/trax). I have also updated the code in the [vot-toolkit](https://github.com/alessiodore/vot-toolkit) fork in the case you want to test it within the tool. Please do let me know if it works for you as I tested it only in Linux (Ubuntu 14.04).

**Comment by lukacu** [comment]
Great, thanks. I will try to have a look in the next week. The code looks now much more complete and I presume that it can be used to perform the current VOT experiments. After testing it myself I will merge it.

**Comment by lukacu** [comment]
Initial Python support added in 6aa6f7866578db9d390936f49b7dc84edb89ff6f, closing issue. All the bugs in the implementation should be now addressed in separate issues.
