### ISSUE TITLE
no matching function for call to ‘trax::Server::wait

### ISSUE THREAD

**Issue by wumingdabei** [votchallenge/trax#56]
I met a compile problem：
main_trax.cpp:20:44: error: no matching function for call to ‘trax::Server::wait(trax::Image&, trax::Region&, trax::Properties&)’  int tr = handle.wait(img, reg, prop);

Could you please give me some advice?

**Comment by luoveh** [comment]
Function Server::wait in trax.h is "int wait(Image& image, Region& region, Properties& properties)" , but in traxpp.cpp is "int Server::wait(ImageList& image, Region& region, Properties& properties)" .

**Comment by lukacu** [comment]
I am not sure that this is true, it would not compile at all in this case, but maybe it was a problem with some version in between. Both the definition and declaration match in the source now.
