### ISSUE TITLE
TraX support not found. Please add trax module to Python path.

### ISSUE THREAD

**Issue by xiuruisi** [votchallenge/trax#57]
Hi, I'm trying to  configure vot-toolkit, but  always have this problem.  I try some tips,but make no difference, I try to give up matlab version and configure python version. These two ways have the same problem.
This is python version log.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cs512/jixie/vot-toolkit-master/tracker/examples/python/python_ncc.py", line 3, in <module>
    import vot
  File "/home/cs512/jixie/vot-toolkit-master/tracker/examples/python/vot.py", line 19, in <module>
    raise Exception('TraX support not found. Please add trax module to Python path.')
Exception: TraX support not found. Please add trax module to Python path.

What should  I do ? thanks.

**Comment by lukacu** [comment]
This means simply that the Python trax package was not found by the Python. Hopefully, this will be now easier when the new version will be merged to master and the package will be available for installation by pip.
