### ISSUE TITLE
Unable to compile MEX function

### ISSUE THREAD

**Issue by tianlewangzhe** [votchallenge/trax#60]
使用 'MinGW64 Compiler (C++)' 编译。
MEX 已成功完成。
使用 'MinGW64 Compiler (C++)' 编译。
ERROR: Unable to compile MEX function: "F:\VOT\vot-toolkit-master-8-8\vot-toolkit-master\native\trax\src\message.c:52:24: fatal error: sys/socket.h: No such file or directory
compilation terminated.
".
错误使用 initialize_native (line 87)
Unable to compile all native resources.

出错 workspace_create (line 143)
initialize_native();

Trax will have the following error. If you delete the header file prompted below, it will show undefined.

**Comment by lukacu** [comment]
My guess is that this has something to do with MinGW compiler. I have usually used Visual Studio to compile C++ on Windows.
