### ISSUE TITLE
trax_server_wait

### ISSUE THREAD

**Issue by maidencc** [votchallenge/trax#63]
Hello, there is a problem with trax.

When I run my program , it shows no results and no errors. You can only force interrupts, and this is the message after the interrupt.

Traceback (most recent call last):
  File "/home/elisa/vrpt/tools/test.py", line 293, in <module>
    handle = vot.VOT("mask")
  File "/home/elisa/vrpt/tools/vot.py", line 50, in __init__
    request = self._trax.wait()
  File "/home/elisa/anaconda3/envs/vrpt/lib/python3.7/site-packages/trax/server.py", line 94, in wait
    status = TraxStatus.decode(trax_server_wait(self._handle.reference, byref(timage), byref(tregion), tproperties))
KeyboardInterrupt

When I step through pyCharm, I run to this line
Status = traxstatus. decode(trax_server_wait(self._handle.reference, byref(Timage), Byref (Tregion), tProperties))

Variables shows 'Connected' and does not respond.

![QQ截图20210824162808](https://user-images.githubusercontent.com/50616565/130584098-34258a96-c1c1-401c-ae3c-0f0a59fdb90e.png)

What is the reason for this?

**Comment by lukacu** [comment]
Do you run your tracker from the VOT toolkit or as standalone program?
