### ISSUE TITLE
vot.tracker.TrackerException: Server terminated the session

### ISSUE THREAD

**Issue by tahiira** [votchallenge/trax#64]
Hello every body,
I want to test Atom tracker with votlt2020 dataset, but when I want evaluate it, I faced with this error:
```
"File "/home/user/pytracking_env/lib/python3.6/site-packages/vot/tracker/trax.py", line 409, in _error
    tracker_log=log if not self._output is None else None)
vot.tracker.TrackerException: Server terminated the session"
```

how can I resolve it?

**Comment by lukacu** [comment]
The most common reason for this message is that the tracker send a quit message. This can happen due to numerous reasons, please check tracker log for more details.
