### ISSUE TITLE
Error during tracker execution: Exception when sending frame to tracker: Client not alive

### ISSUE THREAD

**Issue by dev-lyj** [votchallenge/trax#66]
在测试过程中，出现这个问题

**Comment by lukacu** [comment]
Please post questions in english. The error that you have posted in the title only tells that the client (tracker) process has crashed or terminated and is not alive anymore.

**Comment by lukacu** [comment]
Just another comment: the "client" in this case is a bit misleading, the tracker is usually referred to as server. I will check if I can correct this, but the cause remains the same.

**Comment by dev-lyj** [comment]
> Just another comment: the "client" in this case is a bit misleading, the tracker is usually referred to as server. I will check if I can correct this, but the cause remains the same.

Updating on frame 32/49
@@Trax:frame "file:///tmp/vot_dummy_50_640_480/color/00000033.jpg"
@@Trax:state "190.0244,85.6347,97.8675,110.5902"
Updating on frame 33/49
@@Trax:frame "file:///tmp/vot_dummy_50_640_480/color/00000034.jpg"
@@Trax:state "201.9191,76.2010,97.8675,110.5902"
Updating on frame 34/49
@@Trax:frame "file:///tmp/vot_dummy_50_640_480/color/00000035.jpg"
Timeout reached, terminating tracker
@@Trax:quit
@@Trax:state "215.4543,68.4080,97.8675,110.5902"
Updating on frame 35/49
Error during tracker execution: Exception when sending frame to tracker: Client not alive
