### ISSUE TITLE
ERROR: Could not build wheels for vot-trax

### ISSUE THREAD

**Issue by firelgh** [votchallenge/trax#69]
-----------------------------------------------------------------------------
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting vot-trax==4.0.1
  Using cached http://mirrors.aliyun.com/pypi/packages/71/bf/c1dbff143fbb2537427bb87798ded81b3bd0c8be4a46882f904dbc0ce4f6/vot-trax-4.0.1.tar.gz (62 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.16 in d:\programdata\anaconda3\envs\seqtrack\lib\site-packages (from vot-trax==4.0.1) (1.24.3)
Requirement already satisfied: six in d:\programdata\anaconda3\envs\seqtrack\lib\site-packages (from vot-trax==4.0.1) (1.16.0)
Building wheels for collected packages: vot-trax
  Building wheel for vot-trax (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vot-trax
  Running setup.py clean for vot-trax
Failed to build vot-trax
ERROR: Could not build wheels for vot-trax, which is required to install pyproject.toml-based projects

----------------------------------------------------------------------------------
Please! How to solve this? Not even after the pyproject is installed.

**Comment by lukacu** [comment]
Well, the error is pretty verbose; it looks like you do not have a suitable compiler to compile the native part of the library. At some point we may provide pre-built wheels, but this requires a lot of work to get it right.

**Comment by lukacu** [comment]
Not there are some pre-built wheels available for Windows and Linux, Please try installing the latest version and see if it works without compiling.
